#! /bin/sh
#
# Stop on error and output every command before executing it
set -ex

echo "[cibuild] started at..."
date "+%H:%M:%S"

export RAILS_ENV="test"
export RACK_ENV="test"
export CI="CIJOE"

hostname

bundle install
bundle exec rake db:test:prepare

yarn install

echo "[cibuild] Check JS properly formatted"
yarn run format
git diff --exit-code --quiet || {
    echo "yarn run format changed source files"
    echo "Please run: yarn run format"
    exit 1
}

echo "[cibuild] Running tests ..."
date "+%H:%M:%S"

# run tests.
script/test

echo "[cibuild] Running system tests ..."
date "+%H:%M:%S"
SKIP_SIMPLECOV=1 bundle exec rails spec:system

echo "[cibuild] Running data tests ..."
date "+%H:%M:%S"
SKIP_SIMPLECOV=1 bundle exec rails spec:data_test
