#! /bin/sh
#
# Stop on error and output every command before executing it
set -ex

echo "[cibuild] started at..."
date "+%H:%M:%S"

export RAILS_ENV="test"
export RACK_ENV="test"
export CI="CIJOE"

hostname

echo "[cibuild] Running tests ..."
date "+%H:%M:%S"

# run tests.
script/test

echo "[cibuild] Running system tests ..."
date "+%H:%M:%S"
SKIP_SIMPLECOV=1 bundle exec rails spec:system

echo "[cibuild] Running data tests ..."
date "+%H:%M:%S"
SKIP_SIMPLECOV=1 bundle exec rails spec:data_test
