#!/bin/bash
FULL_VERSION=$1

DESCRIBE=`git describe --tags --always`
echo $DESCRIBE
# increment the build number (ie 115 to 116)
VERSION=`echo $DESCRIBE | awk '{split($0,a,"-"); print a[1]}'`
BUILD=`echo $DESCRIBE | awk '{split($0,a,"-"); print a[2]}'`
PATCH=`echo $DESCRIBE | awk '{split($0,a,"-"); print a[3]}'`

echo "version $DESCRIBE =>  VERSION:${VERSION} BUILD:${BUILD} PATCH:${PATCH}"

DOCKER_TAG=${VERSION}"."${BUILD}"."${PATCH}

echo "building image with tags :  ${DOCKER_TAG} based on ${VERSION}    patch ${PATCH} ($DESCRIBE)"
docker build -t blsq/hesabu:$DOCKER_TAG --build-arg DOCKER_TAG=$DOCKER_TAG --file Dockerfile.build .

echo "Next step to monitor the size, for the moment let's log it"
docker images blsq/hesabu