#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

if [ -f "config/database.yml" ] ; then
    true
else
    echo "==> Generating config/database.yml"
    cp config/database-template.yml config/database.yml
fi

if [ -f "config/application.yml" ] ; then
    true
else
    echo "==> Generating config/application.yml"
    cp config/application.template.yml config/application.yml
fi

echo "==> Setting up DB…"
# reset database to a fresh state.
bin/rake db:reset db:create

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
    # Only things for a development environment will run inside here
    # Do things that need to be done to the application to set up for the first
    # time. Or things needed to be run to to reset the application back to first
    # use experience. These things are scoped to the application's domain.
    echo "==> Seeding some default data…"
    bin/rake db:seed
fi

echo "==> App is now ready to go!"
